### PR TITLE
Fix typos in Menaion

### PR DESCRIPTION
**Pull request by typiconman**
Please review. Two questions:

1. Here, I am correcting errors in the text that are not OCR errors, but are typos in the scanned printed text (see here:
http://www.ponomar.net/cgi-bin/bookpage.cgi?id=5b9c7625-d123-11e0-b163-a7bef95daa3f&page=95
and here:
http://www.ponomar.net/cgi-bin/bookpage.cgi?id=5b9c7625-d123-11e0-b163-a7bef95daa3f&page=94 )
It seems to me that we *should* correct these errors, but should we somehow keep track of them?

2. What is the status of the Markdown project? Should I work with the XML files or wait for conversion to md?

### CODE REVIEW

**Comment by pgmmpk** [comment]
1. Lets create Erratum section where we can log the corrections.
2. I suggest we treat Markdown as a research project. I do not want it to be a stopper in our plans. If/when it works, we will just replace the corpus (or maintain parallel XML and Markdown corpora).

**Comment by typiconman** [comment]
Would it be possible to have the Erraturm logged automatically (or by running a script)?

**Comment by pgmmpk** [comment]
Not sure I understand. What script will compare? Maybe we shall keep errata changes in a separate branch. Then by comparing branches we may be able to generate automatic Errata. But then we will have a pain of synching two branches... Another possibility is to log somewhere commit ids that introduce errata changes. Then scrip may be able to generate errata chapter from commit diffs...

All feels overly complicated. I think its okay not to keep any notes, blaming the discrepancy on OCR error, if somebody sues us :P

**Comment by typiconman** [comment]
I'm thinking maybe of keeping a file, like ERROR.md (see  706870e), where we keep track of commits that fix typos or other errors in the corpus. In the future, we could go back and see what changes were made using git. I think this would be useful down the road.

**Comment by typiconman** [comment]
Of course, the downside of this approach is that it requires two commits -- first of the fix, then of the error log. Maybe a better way would be to put some information in the commit message?

**Comment by pgmmpk** [comment]
I like the idea of marking commit message. For example, adding @erratum to the message text will allow us to automatically find them and generate ERROR.md or ERROR.xml

**Pull request closed without merging**
