### PR TITLE
Add xslt

### PR DESCRIPTION
**Pull request by typiconman**
Adding XSL transform to convert XML -> HTML for text pages and manifest file.
Please review @pgmmpk 

Also, to discuss: if manifest.xml is the best way to store the metadata, and what the book reader interface should look like.

### CODE REVIEW

**Comment by pgmmpk** [comment]
I have no opinion on the UI. I think we should develop an API to access scanned text and images. What can be built on top of this is entirely different thing. HTML conversion and styling depends on the end-user application, it can change often and depends on the site that is embedding this information.

For that reason, it seems to me that XML should not have XSLT link embedded. Having XSLT link
in the XML mixes data with presentation. Again, data is more valuable and persistent, while presentation varies and is volatile.

**Comment by typiconman** [comment]
We can get rid of the XSLT line in the XML files. Anyway, converting the XML to HTML will require an external program in addition to the XSLT in order to generate all of the links, etc.

I do think we should keep XSLT, CSS and the scripts in the util/ folder. It would be useful to have utilities hosted together with the XML data.

**Comment by pgmmpk** [comment]
No strong opinion here. Please, drive these changes.

**Comment by typiconman** [comment]
@pgmmpk I removed all XSLT references from the XML data files.

**Pull request merged**
